/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const after_Purchases_Create = require('./code/after-purchases-create');
const after_Redemptions_Create = require('./code/after-redemptions-create');

class my_Project_2Srv extends LCAPApplicationService {
    async init() {

        this.after('CREATE', 'Purchases', async (results, request) => {
            await after_Purchases_Create(results, request);
        });

        this.after('CREATE', 'Redemptions', async (results, request) => {
            await after_Redemptions_Create(results, request);
        });

        return super.init();
    }
}


module.exports = {
    my_Project_2Srv
};